let Q=[];
(async()=>{try{
const src=await fetch('questions-source.html',{cache:'no-cache'}).then(r=>r.text());
const m=src.match(/const Q=(\[\[.*?\]\]);let V=/s);if(!m)throw new Error('問題データを読み込めませんでした');Q=JSON.parse(m[1]);
const fi=Q.findIndex(x=>x[0]===1&&String(x[2]).includes('成果を生み出す四つのファクター「'));
Q=Q.filter(x=>!(x[0]===1&&String(x[2]).includes('成果を生み出す四つのファクター「')));
Q.splice(fi<0?Q.length:fi,0,
[1,'穴埋め','成果を生み出す四つのファクターを4つ答える。','アタマ・ムネ・オナカ・テアシ','四つのファクターは「アタマ・ムネ・オナカ・テアシ」。'],
[1,'穴埋め','成果を生み出す四つのファクターを、大事な順番で答える。','テアシ→アタマ→オナカ→ムネ','原本メモの順番は「テアシ→アタマ→オナカ→ムネ（テアオム）」。'],
[1,'教訓','成果を生み出す四つのファクターのうち、アタマとムネはそれぞれ何を意味するか答える。','アタマ＝行動の結果をしっかりと考え抜く／ムネ＝人のためになにかをやってあげる気持ちを持つこと','それぞれの意味を正確に覚える。'],
[1,'教訓','成果を生み出す四つのファクターのうち、オナカとテアシはそれぞれ何を意味するか答える。','オナカ＝失敗を恐れない勇気と失敗を認める勇気／テアシ＝行動をすること','それぞれの意味を正確に覚える。']);
init();}catch(e){document.getElementById('app').innerHTML='<div class="box empty">'+e.message+'</div>'}})();
function init(){
const app=document.getElementById('app'),st=document.getElementById('st'),sd=document.getElementById('sd'),sr=document.getElementById('sr'),sw=document.getElementById('sw');
let vols=JSON.parse(localStorage.getItem('waytest-volumes-v1')||'[1,2,6]').map(Number).filter(v=>[1,2,6].includes(v));if(!vols.length)vols=[1,2,6];
let mode='exam',quiz=[],idx=0,run=null,lock=false;
const S=JSON.parse(localStorage.getItem('waytest-v1')||'{}'),H=JSON.parse(localStorage.getItem('waytest-history-v1')||'[]');
const saveS=()=>localStorage.setItem('waytest-v1',JSON.stringify(S)),saveH=()=>localStorage.setItem('waytest-history-v1',JSON.stringify(H.slice(0,100))),saveV=()=>localStorage.setItem('waytest-volumes-v1',JSON.stringify(vols));
const key=x=>x[0]+'-'+Q.indexOf(x),pool=()=>Q.filter(x=>vols.includes(x[0])),weak=()=>pool().filter(x=>{let s=S[key(x)];return s&&(s.ng||0)+(s.mid||0)>(s.ok||0)}),shuffle=a=>[...a].sort(()=>Math.random()-.5),esc=s=>(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])),norm=s=>(s||'').normalize('NFKC').toLowerCase().replace(/[\s　・、,。．\.\/／→⇒＝=「」『』（）()［］\[\]：:;；!！?？]/g,'');
function mark(x,r){let k=key(x);S[k]??={ok:0,ng:0,mid:0};S[k][r]=(S[k][r]||0)+1;saveS()}
function vt(v=vols){return v.slice().sort((a,b)=>a-b).map(n=>'第'+n+'巻').join('・')}function fmt(d){return new Date(d).toLocaleString('ja-JP',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})}
function buttons(){document.querySelectorAll('[data-v]').forEach(b=>b.classList.toggle('on',vols.includes(+b.dataset.v)))}function stats(){st.textContent=pool().length;sd.textContent=H.length;if(H.length){sr.textContent=(H.reduce((a,h)=>a+h.score,0)/H.length).toFixed(1)+'/10';sw.textContent=H[0].score+'/10'}else sr.textContent=sw.textContent='—'}
document.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>{let v=+b.dataset.v;if(vols.includes(v)){if(vols.length===1)return alert('1巻以上選んでください');vols=vols.filter(n=>n!==v)}else vols.push(v);vols.sort();saveV();render()});
document.querySelectorAll('[data-m]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-m]').forEach(x=>x.classList.remove('on'));b.classList.add('on');mode=b.dataset.m;render()});
function render(){buttons();stats();({exam:examHome,learn:learn,fill:()=>startPractice(pool().filter(x=>x[1]==='穴埋め'),'穴埋め練習'),lesson:()=>startPractice(pool().filter(x=>x[1]!=='穴埋め'),'概要練習'),weak:()=>startPractice(weak(),'苦手復習'),history:history}[mode])()}
function charPadHTML(){return `<div class="charbox"><div class="handlabel">1文字ずつ手書き <span>書き終わると自動で文字確定</span></div><div class="assembled" id="assembled">まだ入力されていません</div><div class="charrow"><canvas id="charpad" class="charpad"></canvas><div class="charhelp"><b>次の1文字</b><div id="charstatus">書いてください</div></div></div><div id="charcands"></div><div class="acts"><button class="b" id="undoChar">← 1文字戻す</button><button class="b danger" id="clearAnswer">全部消す</button></div></div>`}
function setupCharPad(){
const c=document.getElementById('charpad'),ctx=c.getContext('2d'),out=document.getElementById('assembled'),status=document.getElementById('charstatus'),candBox=document.getElementById('charcands');let strokes=[],cur=null,chars=[],timer=null,busy=false,start=Date.now(),lastCandidates=[];
function redraw(){let r=c.getBoundingClientRect();ctx.clearRect(0,0,r.width,r.height);ctx.fillStyle='#fff';ctx.fillRect(0,0,r.width,r.height);ctx.strokeStyle='#e6eaf1';ctx.lineWidth=1;ctx.setLineDash([4,4]);ctx.beginPath();ctx.moveTo(r.width/2,0);ctx.lineTo(r.width/2,r.height);ctx.moveTo(0,r.height/2);ctx.lineTo(r.width,r.height/2);ctx.stroke();ctx.setLineDash([]);ctx.strokeStyle='#111827';ctx.lineWidth=4;ctx.lineCap='round';ctx.lineJoin='round';strokes.forEach(s=>{if(!s.length)return;ctx.beginPath();ctx.moveTo(s[0].x,s[0].y);s.slice(1).forEach(p=>ctx.lineTo(p.x,p.y));ctx.stroke()})}
function resize(){let r=c.getBoundingClientRect(),d=Math.max(1,devicePixelRatio||1);c.width=Math.round(r.width*d);c.height=Math.round(r.height*d);ctx.setTransform(d,0,0,d,0,0);redraw()}function pos(e){let r=c.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top,t:Date.now()-start}}
function refresh(){out.textContent=chars.length?chars.join(''):'まだ入力されていません'}function resetInk(){strokes=[];cur=null;start=Date.now();redraw()}
function schedule(){clearTimeout(timer);timer=setTimeout(recognizeOne,900)}
c.addEventListener('pointerdown',e=>{if(busy)return;e.preventDefault();clearTimeout(timer);c.setPointerCapture(e.pointerId);cur=[pos(e)];strokes.push(cur)});c.addEventListener('pointermove',e=>{if(!cur||busy)return;e.preventDefault();cur.push(pos(e));redraw()});c.addEventListener('pointerup',e=>{if(!cur||busy)return;e.preventDefault();cur=null;redraw();schedule()});c.addEventListener('pointercancel',()=>{cur=null;schedule()});
async function recognizeOne(){if(busy||!strokes.some(s=>s.length>1))return;busy=true;status.textContent='認識中…';try{let r=c.getBoundingClientRect(),ink=strokes.filter(s=>s.length>1).map(s=>[s.map(p=>Math.round(p.x)),s.map(p=>Math.round(p.y)),s.map(p=>Math.round(p.t))]),body={app_version:0.4,api_level:'537.36',device:navigator.userAgent,input_type:0,options:'enable_pre_space',requests:[{writing_guide:{writing_area_width:Math.round(r.width),writing_area_height:Math.round(r.height)},pre_context:'',max_num_results:10,max_completions:0,ink}]},res=await fetch('https://inputtools.google.com/request?itc=ja-t-i0-handwrit&app=demopage',{method:'POST',headers:{'Content-Type':'application/json; charset=UTF-8'},body:JSON.stringify(body)}),j=await res.json();if(!Array.isArray(j)||j[0]!=='SUCCESS'||!j[1]?.[0]?.[1])throw 0;let raw=j[1][0][1].filter(Boolean),cands=[];raw.forEach(x=>{let ch=Array.from(x)[0];if(ch&&!cands.includes(ch))cands.push(ch)});if(!cands.length)throw 0;lastCandidates=cands.slice(0,6);chars.push(lastCandidates[0]);refresh();candBox.innerHTML='<div class="candlabel">今の文字：候補をタップすると修正</div>'+lastCandidates.map((x,n)=>`<button class="cand ${n===0?'sel':''}" data-c="${esc(x)}">${esc(x)}</button>`).join('');candBox.querySelectorAll('[data-c]').forEach(b=>b.onclick=()=>{chars[chars.length-1]=b.dataset.c;refresh();candBox.querySelectorAll('.cand').forEach(x=>x.classList.toggle('sel',x===b))});status.textContent='「'+lastCandidates[0]+'」を確定。次の文字を書いてください';resetInk()}catch{status.textContent='認識できません。もう一度書いてください';resetInk()}finally{busy=false}}
document.getElementById('undoChar').onclick=()=>{clearTimeout(timer);if(strokes.length){strokes=[];redraw()}else chars.pop();candBox.innerHTML='';refresh();status.textContent='次の1文字を書いてください'};document.getElementById('clearAnswer').onclick=()=>{clearTimeout(timer);chars=[];candBox.innerHTML='';resetInk();refresh();status.textContent='最初の1文字を書いてください'};resize();setTimeout(resize,50);return{value:()=>chars.join(''),isBusy:()=>busy,flush:async()=>{clearTimeout(timer);if(strokes.some(s=>s.length>1))await recognizeOne()}}}
function examHome(){let h=H[0],p=H[1],d=h&&p?h.score-p.score:null;app.innerHTML=`<div class="box"><div class="ttl">本番10問</div><div class="q">${vt()} からランダムで10問</div><div class="sub">穴埋めは1文字ずつ手書き認識して回答欄へ確定。概要・教訓はキーボード入力です。</div><div class="acts"><button class="pri" id="start">10問テストを開始</button></div>${h?`<div class="card"><div class="meta">直近 ${fmt(h.date)}｜${vt(h.volumes)}</div><div class="score">${h.score}/10点 ${d===null?'':`<span class="delta ${d>0?'up':d<0?'down':'flat'}">${d>0?'↑ +':d<0?'↓ ':''}${d}</span>`}</div></div>`:''}</div>`;document.getElementById('start').onclick=()=>{quiz=shuffle(pool()).slice(0,10);idx=0;run={date:new Date().toISOString(),volumes:[...vols],answers:[]};showExam()}}
function showExam(){lock=false;let x=quiz[idx],hand=x[1]==='穴埋め';app.innerHTML=`<div class="card"><div class="meta">本番10問｜${vt(run.volumes)}｜第${x[0]}巻｜${x[1]}｜${idx+1}/10</div><div class="prog"><i style="width:${idx*10}%"></i></div><div class="q">${x[2]}</div>${hand?charPadHTML():'<textarea id="txt" placeholder="概要・重要なことを入力"></textarea>'}<div class="acts"><button class="pri" id="judgeBtn">${hand?'回答を判定':'答え合わせ'}</button></div><div class="ans" id="ans"><b>正答例：</b>${x[3]}<div class="exp">${x[4]}</div></div><div class="acts" id="grade" style="display:none"></div></div>`;let cp=hand?setupCharPad():null,txt=hand?null:document.getElementById('txt'),btn=document.getElementById('judgeBtn'),ans=document.getElementById('ans'),grade=document.getElementById('grade');btn.onclick=async()=>{if(hand){btn.disabled=true;await cp.flush();btn.disabled=false;let v=cp.value();if(!v)return alert('回答を入力してください');let ok=norm(v)===norm(x[3]);ans.classList.add('show');grade.style.display='flex';grade.innerHTML=`<div class="recog ${ok?'recogok':'recogng'}"><b>${ok?'○ 正解':'× 不正解'}</b><div class="recogtext">あなたの回答：${esc(v)}</div></div><button class="pri" id="next">${ok?'次の問題':'不正解として次へ'}</button>${!ok?'<button class="b" id="override">認識ミスなので正解扱い</button>':''}`;btn.style.display='none';document.getElementById('next').onclick=()=>commit(ok?'ok':'ng');if(!ok)document.getElementById('override').onclick=()=>commit('ok')}else{if(!txt.value.trim()&&!confirm('未記入で答えを見ますか？'))return;txt.disabled=true;ans.classList.add('show');grade.style.display='flex';grade.innerHTML='<button class="pri" data-g="ok">○ 正解</button><button class="b danger" data-g="ng">× 不正解</button>';btn.style.display='none';grade.querySelectorAll('[data-g]').forEach(b=>b.onclick=()=>commit(b.dataset.g))}};function commit(r){if(lock)return;lock=true;mark(x,r);run.answers.push({key:key(x),v:x[0],q:x[2],result:r});if(++idx<10)showExam();else finish()}}
function finish(){let score=run.answers.filter(a=>a.result==='ok').length;run.score=score;run.date=new Date().toISOString();H.unshift(run);saveH();let prev=H[1],d=prev?score-prev.score:null,w=run.answers.filter(a=>a.result==='ng');app.innerHTML=`<div class="box"><div class="ttl">本番10問 結果</div><div class="score">${score}/10点 ${d===null?'':`<span class="delta ${d>0?'up':d<0?'down':'flat'}">${d>0?'↑ +':d<0?'↓ ':''}${d}点</span>`}</div><div class="sub">${fmt(run.date)}｜${vt(run.volumes)}</div><div class="acts"><button class="pri" id="again">もう一度</button><button class="b" id="hist">記録・傾向</button></div></div><div class="box"><div class="ttl">今回の間違い</div>${w.length?w.map(a=>`<div class="rankitem">第${a.v}巻｜${esc(a.q)}</div>`).join(''):'<div class="good">全問正解！</div>'}</div>`;document.getElementById('again').onclick=examHome;document.getElementById('hist').onclick=()=>{mode='history';document.querySelectorAll('[data-m]').forEach(b=>b.classList.toggle('on',b.dataset.m==='history'));render()};stats()}
function startPractice(a,title){if(!a.length){app.innerHTML='<div class="box empty">対象問題がありません。</div>';return}quiz=shuffle(a);idx=0;showPractice(title)}
function showPractice(title){lock=false;let x=quiz[idx],hand=x[1]==='穴埋め';app.innerHTML=`<div class="card"><div class="meta">${title}｜第${x[0]}巻｜${x[1]}｜${idx+1}/${quiz.length}</div><div class="q">${x[2]}</div>${hand?charPadHTML():'<textarea id="ptxt" placeholder="概要・重要なことを入力"></textarea>'}<div class="acts"><button class="pri" id="pbtn">${hand?'回答を判定':'答え・要点を見る'}</button></div><div class="ans" id="pans"><b>答え：</b>${x[3]}<div class="exp">${x[4]}</div></div><div class="acts" id="pgrade" style="display:none"></div></div>`;let cp=hand?setupCharPad():null,txt=hand?null:document.getElementById('ptxt'),btn=document.getElementById('pbtn'),ans=document.getElementById('pans'),grade=document.getElementById('pgrade');btn.onclick=async()=>{if(hand){btn.disabled=true;await cp.flush();btn.disabled=false;let v=cp.value();if(!v)return alert('回答を入力してください');let ok=norm(v)===norm(x[3]);ans.classList.add('show');grade.style.display='flex';grade.innerHTML=`<div class="recog ${ok?'recogok':'recogng'}"><b>${ok?'○ 正解':'× 不正解'}</b><div class="recogtext">あなたの回答：${esc(v)}</div></div><button class="pri" id="pn">次の問題</button>`;btn.style.display='none';document.getElementById('pn').onclick=()=>commit(ok?'ok':'ng')}else{if(!txt.value.trim()&&!confirm('未記入で答えを見ますか？'))return;txt.disabled=true;ans.classList.add('show');grade.style.display='flex';grade.innerHTML='<button class="b" data-g="ok">できた</button><button class="b" data-g="mid">あやしい</button><button class="b" data-g="ng">できなかった</button>';btn.style.display='none';grade.querySelectorAll('[data-g]').forEach(b=>b.onclick=()=>commit(b.dataset.g))}};function commit(r){if(lock)return;lock=true;mark(x,r);if(++idx<quiz.length)showPractice(title);else render()}}
function learn(){app.innerHTML='<div class="box"><div class="ttl">学習カード</div><input id="sea" placeholder="キーワード検索"><div id="cards"></div></div>';let sea=document.getElementById('sea'),cards=document.getElementById('cards'),f=()=>{let k=sea.value.toLowerCase(),a=pool().filter(x=>!k||(x[2]+x[3]+x[4]).toLowerCase().includes(k));cards.innerHTML=a.map((x,n)=>`<div class="card"><div class="meta">第${x[0]}巻｜${x[1]}</div><div class="q">${x[2]}</div><div class="ans" id="a${n}"><b>答え：</b>${x[3]}<div class="exp">${x[4]}</div></div><button class="b" onclick="document.getElementById('a${n}').classList.toggle('show')">答えを見る</button></div>`).join('')};sea.oninput=f;f()}
function history(){if(!H.length){app.innerHTML='<div class="box empty">本番記録はまだありません。</div>';return}let agg={};H.forEach(h=>(h.answers||[]).forEach(a=>{let z=agg[a.key]??={v:a.v,q:a.q,ok:0,ng:0};z[a.result]++;agg[a.key]=z}));let vals=Object.values(agg),w=vals.filter(x=>x.ng).sort((a,b)=>b.ng-a.ng).slice(0,5),g=vals.filter(x=>x.ok).sort((a,b)=>b.ok-a.ok).slice(0,5);app.innerHTML=`<div class="box"><div class="ttl">点数の推移</div>${H.slice(0,20).map((h,n)=>`<div class="hrow"><div class="hhead"><b>${fmt(h.date)}｜${vt(h.volumes)}</b><div class="score">${h.score}/10</div></div></div>`).join('')}</div><div class="box"><div class="ttl">よく間違えるところ</div>${w.map(x=>`<div class="rankitem">第${x.v}巻｜${esc(x.q)}<div class="rankmeta">不正解${x.ng}回／正解${x.ok}回</div></div>`).join('')||'まだありません'}</div><div class="box"><div class="ttl">よく合っているところ</div>${g.map(x=>`<div class="rankitem">第${x.v}巻｜${esc(x.q)}<div class="rankmeta">正解${x.ok}回／不正解${x.ng}回</div></div>`).join('')}</div>`}
render();
}