(()=>{
const URL='https://gwmwynjkhxaywknhakcw.supabase.co',KEY='sb_publishable_lGmCtn4giQA0585yjQb5yw_a9ptkN6Q',TABLE='waytest_user_state';
const KEYS=['waytest-v1','waytest-history-v1','waytest-volumes-v1','waytest-question-seen-v3','waytest-question-seen-v2','waytest-memorandum-v1'],META='waytest-cloud-meta-v3',DIRTY='waytest-cloud-dirty-v3',BACKUP='waytest-data-backups-v1';
let client=null,user=null,applying=false,timer=null,busy=false,status='未ログイン';
const nSet=Storage.prototype.setItem,nRemove=Storage.prototype.removeItem,j=(s,f)=>{try{return JSON.parse(s)}catch{return f}},snap=()=>{const o={};KEYS.forEach(k=>{const v=localStorage.getItem(k);if(v!==null)o[k]=v});return o};
function meaningful(v=snap()){const h=j(v['waytest-history-v1']||'[]',[]),s=j(v['waytest-v1']||'{}',{}),m=j(v['waytest-memorandum-v1']||'{}',{});return (Array.isArray(h)&&h.length)||Object.keys(s||{}).length||Object.keys(m?.stats||{}).length}
function backup(reason){try{const d=snap();if(!Object.keys(d).length)return;let a=j(localStorage.getItem(BACKUP)||'[]',[]);if(!Array.isArray(a))a=[];a.unshift({date:new Date().toISOString(),signature:JSON.stringify(d),data:d,reason});nSet.call(localStorage,BACKUP,JSON.stringify(a.slice(0,10)))}catch{}}
function getMeta(){return j(localStorage.getItem(META)||'null',null)}function setMeta(t){nSet.call(localStorage,META,JSON.stringify({userId:user?.id,lastCloudUpdatedAt:t||null,syncedAt:new Date().toISOString()}));nRemove.call(localStorage,DIRTY)}
function stats(s){const x=j(s||'{}',{});return x&&typeof x==='object'&&!Array.isArray(x)?x:{}}function mergeStats(a,b){const o={};for(const k of new Set([...Object.keys(a),...Object.keys(b)])){const x=a[k]||{},y=b[k]||{};o[k]={ok:Math.max(+x.ok||0,+y.ok||0),ng:Math.max(+x.ng||0,+y.ng||0),mid:Math.max(+x.mid||0,+y.mid||0)}}return o}
function mergeHist(a,b){const aa=j(a||'[]',[]),bb=j(b||'[]',[]),m=new Map();[...(Array.isArray(aa)?aa:[]),...(Array.isArray(bb)?bb:[])].forEach(h=>{const k=JSON.stringify([h?.date,h?.score,h?.volumes,h?.answers]);if(!m.has(k))m.set(k,h)});return [...m.values()].sort((x,y)=>new Date(y?.date||0)-new Date(x?.date||0)).slice(0,100)}
function mergeList(a,b){return [...new Set([...(j(a||'[]',[])||[]),...(j(b||'[]',[])||[])])]}
function mergeMemo(a,b){const A=j(a||'{}',{}),B=j(b||'{}',{}),out={...B,...A,stats:{}};for(const k of new Set([...Object.keys(A.stats||{}),...Object.keys(B.stats||{})])){const x=A.stats?.[k]||{},y=B.stats?.[k]||{};out.stats[k]={ok:Math.max(+x.ok||0,+y.ok||0),mid:Math.max(+x.mid||0,+y.mid||0),ng:Math.max(+x.ng||0,+y.ng||0)}}return out}
function merge(local,cloud){const o={...cloud,...local};o['waytest-v1']=JSON.stringify(mergeStats(stats(local['waytest-v1']),stats(cloud['waytest-v1'])));o['waytest-history-v1']=JSON.stringify(mergeHist(local['waytest-history-v1'],cloud['waytest-history-v1']));const lv=j(local['waytest-volumes-v1']||'null',null),cv=j(cloud['waytest-volumes-v1']||'null',null);o['waytest-volumes-v1']=JSON.stringify(Array.isArray(lv)&&lv.length?lv:Array.isArray(cv)&&cv.length?cv:[1,2,6]);o['waytest-question-seen-v3']=JSON.stringify(mergeList(local['waytest-question-seen-v3'],cloud['waytest-question-seen-v3']));o['waytest-question-seen-v2']=JSON.stringify(mergeList(local['waytest-question-seen-v2'],cloud['waytest-question-seen-v2']));o['waytest-memorandum-v1']=JSON.stringify(mergeMemo(local['waytest-memorandum-v1'],cloud['waytest-memorandum-v1']));return o}
function stateValues(s){return s&&s.values&&typeof s.values==='object'?s.values:{}}function apply(v,reason){backup(reason);applying=true;try{KEYS.forEach(k=>nRemove.call(localStorage,k));KEYS.forEach(k=>{if(typeof v[k]==='string')nSet.call(localStorage,k,v[k])})}finally{applying=false}}
function setStatus(t,kind=''){status=t;const e=document.getElementById('cloudStatus');if(e){e.textContent=t;e.style.color=kind==='err'?'#b42318':kind==='ok'?'#087f5b':'#697386'}}
async function getCloud(){const {data,error}=await client.from(TABLE).select('state,updated_at').eq('user_id',user.id).maybeSingle();if(error)throw error;return data}
async function push(v=snap()){if(!user||busy)return false;busy=true;setStatus('クラウドへ保存中…');try{const now=new Date().toISOString(),{data,error}=await client.from(TABLE).upsert({user_id:user.id,state:{format:'waytest-cloud-v4',savedAt:now,values:v},updated_at:now},{onConflict:'user_id'}).select('updated_at').single();if(error)throw error;setMeta(data?.updated_at||now);setStatus('同期済み','ok');return true}catch(e){console.error(e);setStatus('同期に失敗しました。','err');return false}finally{busy=false}}
function schedule(){if(!user||applying)return;nSet.call(localStorage,DIRTY,'1');clearTimeout(timer);timer=setTimeout(()=>push(),900)}
Storage.prototype.setItem=function(k,v){const r=nSet.call(this,k,v);if(this===localStorage&&!applying&&KEYS.includes(String(k)))schedule();return r};Storage.prototype.removeItem=function(k){const r=nRemove.call(this,k);if(this===localStorage&&!applying&&KEYS.includes(String(k)))schedule();return r};
async function activate(u,reloadAfter=false){user=u;render();setStatus('アカウントの記録を確認中…');try{const local=snap(),m=getMeta(),dirty=localStorage.getItem(DIRTY)==='1',row=await getCloud();if(!row){await push(local);setStatus('この端末の記録をアカウントへ保存しました。','ok')}else{const cloud=stateValues(row.state);if(!m||m.userId!==u.id){if(meaningful(local)){const v=merge(local,cloud);apply(v,'before-first-account-merge');await push(v);setStatus('端末の記録を残してクラウドと統合しました。','ok')}else{apply(cloud,'before-cloud-restore');setMeta(row.updated_at);setStatus('アカウントの記録を読み込みました。','ok')}}else if(dirty){const v=merge(local,cloud);apply(v,'before-dirty-merge');await push(v)}else{const ct=new Date(row.updated_at||0).getTime(),lt=new Date(m.lastCloudUpdatedAt||0).getTime();if(ct>lt+1000){apply(cloud,'before-newer-cloud-restore');setMeta(row.updated_at);setStatus('別端末の新しい記録を読み込みました。','ok')}else setStatus('同期済み','ok')}}if(reloadAfter)setTimeout(()=>location.reload(),150)}catch(e){console.error(e);setStatus('クラウド記録の読み込みに失敗しました。','err')}}
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function render(){const note=document.querySelector('.note');if(!note)return;let box=document.getElementById('cloudBox');if(!box){box=document.createElement('div');box.className='box';box.id='cloudBox';note.insertAdjacentElement('afterend',box)}if(!client){box.innerHTML='<div class="ttl">Supabaseアカウント同期</div><div class="sub">同期機能を読み込めませんでした。端末保存はそのまま使えます。</div>';return}if(user){box.innerHTML=`<div class="ttl">Supabaseアカウント同期</div><div class="sub"><b>${esc(user.email||'ログイン中')}</b> の記録として自動保存中です。</div><div class="acts"><button class="pri" id="cloudSyncNow">今すぐ同期</button><button class="b danger" id="cloudLogout">ログアウト</button></div><div class="sub" id="cloudStatus" style="margin-top:7px">${esc(status)}</div>`;document.getElementById('cloudSyncNow').onclick=()=>push();document.getElementById('cloudLogout').onclick=async()=>{if(!await push())return alert('最新記録を保存できなかったためログアウトを中止しました。');if(!confirm('ログアウトします。記録はクラウドに残ります。'))return;backup('before-account-logout');const {error}=await client.auth.signOut({scope:'local'});if(error)return alert(error.message);applying=true;try{KEYS.forEach(k=>nRemove.call(localStorage,k));nRemove.call(localStorage,META);nRemove.call(localStorage,DIRTY)}finally{applying=false}location.reload()}}else{box.innerHTML=`<div class="ttl">Supabaseアカウント同期</div><div class="sub">ログインすると、<b>今この端末にある記録を消さずに</b>アカウント保存へ移行します。</div><input id="cloudEmail" type="email" placeholder="メールアドレス" autocomplete="email"><input id="cloudPass" type="password" placeholder="パスワード" autocomplete="current-password"><div class="acts"><button class="pri" id="cloudLogin">ログインして同期</button><button class="b" id="cloudSignup">新規登録</button></div><div class="sub" id="cloudStatus" style="margin-top:7px">${esc(status)}</div>`;const e=document.getElementById('cloudEmail'),p=document.getElementById('cloudPass');const login=async()=>{if(!e.value.trim()||!p.value)return setStatus('メールアドレスとパスワードを入力してください。','err');setStatus('ログイン中…');const {data,error}=await client.auth.signInWithPassword({email:e.value.trim(),password:p.value});if(error)return setStatus('ログインできませんでした。入力内容を確認してください。','err');if(data?.user)await activate(data.user,true)};document.getElementById('cloudLogin').onclick=login;p.addEventListener('keydown',x=>{if(x.key==='Enter')login()});document.getElementById('cloudSignup').onclick=async()=>{if(!e.value.trim()||!p.value)return setStatus('メールアドレスとパスワードを入力してください。','err');setStatus('登録中…');const {data,error}=await client.auth.signUp({email:e.value.trim(),password:p.value});if(error)return setStatus(error.message,'err');if(data?.session&&data?.user)await activate(data.user,true);else setStatus('登録しました。確認メールが届いた場合はメール内リンクを開いてからログインしてください。','ok')}}}
async function init(){if(!window.supabase?.createClient){status='同期ライブラリ読込エラー';return}client=window.supabase.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storageKey:'nway-supabase-auth-v1'}});window.waytestSupabase=client;const {data,error}=await client.auth.getUser();if(!error&&data?.user)await activate(data.user,false);else{user=null;status='未ログイン'}client.auth.onAuthStateChange((event,session)=>setTimeout(async()=>{if(event==='SIGNED_IN'&&session?.user&&session.user.id!==user?.id)await activate(session.user,false);if(event==='SIGNED_OUT'){user=null;status='未ログイン';render()}},0))}
window.__WAYTEST_SYNC_READY=(async()=>{try{await init()}catch(e){console.error(e);status='同期初期化エラー'}})();window.addEventListener('DOMContentLoaded',()=>{render();window.__WAYTEST_SYNC_READY.finally(render)});window.addEventListener('pagehide',()=>{if(user&&localStorage.getItem(DIRTY)==='1')push()});
})();