(()=>{
  const KEY='waytest-memorandum-v1';
  const TRACKS={
    business:{title:'ビジネス基本10訓',items:[
      {text:'目標と熱意をもって人生、時間は平等、結果は公正。',words:['目標','熱意','平等','公正']},
      {text:'準備して、時間と期限を守れ。己に勝って信用増大。',words:['準備','時間','期限','己','信用増大']},
      {text:'優先順位をつけ実行。一分の速さは力なり。',words:['優先順位','実行','一分','力']},
      {text:'整理・整頓・清掃・清潔・躾。習慣は人格を作る。',words:['整理','整頓','清掃','清潔','躾','習慣','人格']},
      {text:'相談、連絡、報告を多く行え。自分の成長の糧。',words:['相談','連絡','報告','成長','糧']},
      {text:'考え方は幹から先に。森の成果を目指せ。',words:['幹','森','成果']},
      {text:'反復ではなく改善しろ。時間の短縮と結果の向上を。',words:['反復','改善','時間','結果']},
      {text:'良い事はまねて上まわれ。次は新しい企画創造。',words:['まねて','上まわれ','企画創造']},
      {text:'無理に挑戦。知恵、心、勇気で全力行動。',words:['無理','知恵','心','勇気','全力行動']},
      {text:'競争無くして成長なし。ゲーム感覚で自らの幸せを。',words:['競争','成長','ゲーム感覚','幸せ']}
    ]},
    manager:{title:'マネジャー10訓',items:[
      {text:'まず自己マネジメントしろ。世間の目は厳しい。仕事でみんなの手本になれ。',words:['自己マネジメント','世間','仕事','手本']},
      {text:'エバンジェリストたれ。勇気をもっての伝導と許しは部下と自分を磨く。',words:['エバンジェリスト','勇気','伝導','許し','部下','自分']},
      {text:'大きな夢を持てを目標と時と施策と役割優先を記せ。それが計画となる。必ず達成すると人に誓え。',words:['大きな夢','目標','時','施策','役割優先','計画','達成','誓え']},
      {text:'人の目利きをせよ。指導は視ること聞くことから質問へ、企画・参画(2.56)で決定へ。会議では議して決して書して納得して、必ず実行を。',words:['目利き','視る','聞く','質問','企画','参画(2.56)','議して','決して','書して','納得','実行']},
      {text:'相談されたら、即決断、できない時は期日指定で回答を。それが信頼を作る。',words:['即決断','期日指定','回答','信頼']},
      {text:'提案はすべて許可。前提(現状、マイナス、原因、どうすれば、どうなる)をチェックし、コミットを忘れるな。',words:['提案','許可','前提','現状','マイナス','原因','どうすれば','どうなる','コミット']},
      {text:'数字だけを見るな。プロセスを注視せよ。個人別中間チェックによる問題発見と治療が、部下の成長と部門の業績向上に繋がる。',words:['数字','プロセス','個人別中間チェック','問題発見','治療','成長','業績向上']},
      {text:'困難でもあきらめるな。継続して目標に近づく努力をしろ。',words:['困難','あきらめるな','継続','目標','努力']},
      {text:'成果とプロセスに対して、オープンな信賞必罰を、厳しく暖かく行動で示そう。',words:['成果','プロセス','オープン','信賞必罰','厳しく','暖かく','行動']},
      {text:'先を視て、OODAの実践と部下の育成が、リーダーの貢献を拡大し、自己の成長を促す。',words:['先','OODA','部下の育成','リーダーの貢献','自己の成長']}
    ]},
    actions:{title:'マネジャー5つの行動',items:[
      {text:'自ら学び、自ら販買する。',words:['自ら学び','自ら販買']},
      {text:'自ら5Sし、自ら買い場を作る。',words:['自ら5S','自ら買い場']},
      {text:'従業員を観察から質問し、育成を行う。',words:['従業員','観察','質問','育成']},
      {text:'個人名で気配りと信賞必罰を行う。',words:['個人名','気配り','信賞必罰']},
      {text:'自らアイデアを出し、自ら他部門に応援する。',words:['自らアイデア','自ら他部門','応援']}
    ]}
  };
  let active=false,track='business',level='choice',idx=0,selected=[];
  const app=()=>document.getElementById('app');
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const load=()=>{try{const x=JSON.parse(localStorage.getItem(KEY)||'{}');return x&&typeof x==='object'?x:{}}catch{return {}}};
  const state=load(); state.stats??={};
  const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
  const sid=(t,n,l)=>`${t}-${n+1}-${l}`;
  const getStat=(t,n,l)=>state.stats[sid(t,n,l)]||{ok:0,mid:0,ng:0};
  const total=()=>TRACKS[track].items.length;
  function mark(result){const k=sid(track,idx,level);state.stats[k]??={ok:0,mid:0,ng:0};state.stats[k][result]=(state.stats[k][result]||0)+1;state.last={track,level,index:idx,date:new Date().toISOString()};save()}
  const shuffle=a=>[...a].sort(()=>Math.random()-.5);
  function distractors(item){const all=TRACKS[track].items.flatMap(x=>x.words);return shuffle([...new Set(all.filter(w=>!item.words.includes(w)))]).slice(0,Math.min(5,Math.max(3,item.words.length>6?4:3)))}
  function blankify(item){let text=item.text;item.words.forEach((word,i)=>{const at=text.indexOf(word);if(at>=0)text=text.slice(0,at)+`@@${i}@@`+text.slice(at+word.length)});return esc(text).replace(/@@(\d+)@@/g,(_,n)=>`<span class="memoBlank">${selected[+n]?esc(selected[+n]):`＿＿${+n+1}＿＿`}</span>`)}
  function progressSummary(t,l){let ok=0,done=0;TRACKS[t].items.forEach((_,i)=>{const s=getStat(t,i,l),n=(s.ok||0)+(s.mid||0)+(s.ng||0);if(n)done++;if((s.ok||0)>0)ok++});return {ok,done,total:TRACKS[t].items.length}}
  function injectStyle(){if(document.getElementById('memoStyle'))return;const s=document.createElement('style');s.id='memoStyle';s.textContent=`.memoTop{border:2px solid #6b5cff;background:#f8f7ff}.memoHead{display:flex;justify-content:space-between;gap:10px;align-items:center}.memoBadge{font-size:10px;font-weight:800;background:#ebe8ff;color:#5146c7;border-radius:99px;padding:5px 8px}.memoGrid{display:grid;grid-template-columns:repeat(3,1fr);gap:9px;margin-top:10px}.memoChoice{padding:12px;border:1px solid #e2e3f1;border-radius:13px;background:#fff;text-align:left}.memoChoice b{display:block;margin-bottom:4px}.memoLevel{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:10px}.memoBlank{display:inline-block;min-width:64px;margin:2px 3px;padding:3px 6px;border-bottom:2px solid #6b5cff;background:#f0efff;border-radius:6px;font-weight:800;color:#3c348e}.memoWords{display:flex;gap:7px;flex-wrap:wrap;margin-top:12px}.memoWord{border:1px solid #cfd3e4;background:#fff;border-radius:10px;padding:8px 10px;font-weight:750}.memoWord.used{opacity:.35}.memoQ{font-size:16px;font-weight:800;line-height:1.9}.memoAnswer{margin-top:12px;padding:11px;background:#f3f6fc;border-left:4px solid #6b5cff;border-radius:10px;line-height:1.75}.memoResult{margin-top:9px;font-size:13px;font-weight:800}.memoFull{min-height:150px}.memoTiny{font-size:10px;color:#737b8a}.memoScore{display:flex;gap:7px;flex-wrap:wrap;margin-top:8px}.memoScore span{font-size:11px;background:#f3f5fa;border-radius:99px;padding:5px 8px}@media(max-width:700px){.memoGrid{grid-template-columns:1fr}.memoLevel{grid-template-columns:1fr}}`;document.head.appendChild(s)}
  function ensureLauncher(){injectStyle();const main=app();if(!main||document.getElementById('memoLauncher'))return;const box=document.createElement('div');box.className='box memoTop';box.id='memoLauncher';box.innerHTML=`<div class="memoHead"><div><div class="ttl">覚書専用学習</div><div class="sub">第1〜6巻とは混ぜず、各項目を番号順固定で覚えます。</div></div><span class="memoBadge">別枠</span></div><div class="acts"><button class="pri" id="openMemo">覚書を学習する</button></div>`;main.parentElement.insertBefore(box,main);document.getElementById('openMemo').onclick=()=>{active=true;document.querySelectorAll('[data-m]').forEach(x=>x.classList.remove('on'));renderHome()};document.querySelectorAll('[data-m]').forEach(b=>b.addEventListener('click',()=>{active=false;document.getElementById('openMemo')?.classList.remove('on')}));new MutationObserver(()=>{if(active&&!app()?.querySelector('[data-memo-root]'))setTimeout(()=>{if(active)renderQuestionOrHome()},0)}).observe(main,{childList:true,subtree:false})}
  function renderQuestionOrHome(){if(active&&state.sessionStarted)renderQuestion();else renderHome()}
  function renderHome(){state.sessionStarted=false;save();const main=app();if(!main)return;document.getElementById('openMemo')?.classList.add('on');const cards=Object.entries(TRACKS).map(([id,t])=>{const a=progressSummary(id,'choice'),b=progressSummary(id,'full');return `<button class="memoChoice" data-track="${id}"><b>${esc(t.title)}</b><span class="sub">単語選択 ${a.ok}/${a.total}習得｜全文入力 ${b.ok}/${b.total}習得</span></button>`}).join('');main.innerHTML=`<div data-memo-root><div class="box"><div class="memoHead"><div><div class="ttl">覚書</div><div class="sub">各項目は必ず番号順。途中をランダム出題しません。</div></div><span class="memoBadge">順番固定</span></div><div class="memoGrid">${cards}</div></div></div>`;main.querySelectorAll('[data-track]').forEach(b=>b.onclick=()=>{track=b.dataset.track;renderLevel()})}
  function renderLevel(){const main=app(),title=TRACKS[track].title,n=total();main.innerHTML=`<div data-memo-root><div class="box"><div class="ttl">${esc(title)}｜難易度</div><div class="sub">どちらも第1項目から第${n}項目まで順番固定です。</div><div class="memoLevel"><button class="memoChoice" data-level="choice"><b>初級：単語選択で穴埋め</b><span class="sub">重要語を候補から選び、文章を完成させる。</span></button><button class="memoChoice" data-level="full"><b>上級：一から全文入力</b><span class="sub">ヒントなしで文章を最初から入力して覚える。</span></button></div><div class="acts"><button class="b" id="memoBack">← 覚書トップ</button></div></div></div>`;main.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>{level=b.dataset.level;idx=0;state.sessionStarted=true;save();renderQuestion()});document.getElementById('memoBack').onclick=renderHome}
  function renderQuestion(){const main=app(),set=TRACKS[track],item=set.items[idx],st=getStat(track,idx,level),n=set.items.length;selected=[];if(!item)return renderFinish();main.innerHTML=`<div data-memo-root><div class="box"><div class="memoHead"><div><div class="ttl">${esc(set.title)}｜${level==='choice'?'初級・単語選択':'上級・全文入力'}</div><div class="sub">第${idx+1}項目 / ${n}　※順番固定</div></div><span class="memoBadge">${idx+1}/${n}</span></div><div class="prog"><i style="width:${((idx+1)/n)*100}%"></i></div><div class="memoScore"><span>○ ${st.ok||0}</span><span>△ ${st.mid||0}</span><span>× ${st.ng||0}</span></div></div><div class="card" id="memoCard"></div><div class="acts"><button class="b" id="memoQuit">← 難易度選択へ</button><button class="b" id="memoRestart">第1項目からやり直す</button></div></div>`;document.getElementById('memoQuit').onclick=renderLevel;document.getElementById('memoRestart').onclick=()=>{idx=0;renderQuestion()};if(level==='choice')renderChoice(item);else renderFull(item)}
  function renderChoice(item){const card=document.getElementById('memoCard'),options=shuffle([...new Set([...item.words,...distractors(item)])]);function draw(){card.innerHTML=`<div class="meta">重要語を順番にタップして穴を埋める</div><div class="memoQ">${blankify(item)}</div><div class="memoWords">${options.map(w=>`<button class="memoWord ${selected.includes(w)?'used':''}" data-word="${esc(w)}" ${selected.includes(w)?'disabled':''}>${esc(w)}</button>`).join('')}</div><div class="acts"><button class="b" id="memoUndo" ${selected.length?'':'disabled'}>← 1つ戻す</button><button class="pri" id="memoCheck" ${selected.length===item.words.length?'':'disabled'}>答え合わせ</button></div><div class="memoTiny">穴は左から順に埋まります。</div>`;card.querySelectorAll('[data-word]').forEach(b=>b.onclick=()=>{if(selected.length<item.words.length){selected.push(b.dataset.word);draw()}});document.getElementById('memoUndo').onclick=()=>{selected.pop();draw()};document.getElementById('memoCheck').onclick=()=>gradeChoice(item)}draw()}
  function gradeChoice(item){const ok=selected.length===item.words.length&&selected.every((w,i)=>w===item.words[i]);mark(ok?'ok':'ng');const card=document.getElementById('memoCard'),last=idx===total()-1;card.innerHTML=`<div class="meta">第${idx+1}項目｜答え合わせ</div><div class="memoResult" style="color:${ok?'#087f5b':'#b42318'}">${ok?'○ 正解':'× もう一度覚える'}</div><div class="memoAnswer">${esc(item.text)}</div>${ok?'':`<div class="sub" style="margin-top:8px">正しい重要語：${item.words.map(esc).join(' → ')}</div>`}<div class="acts"><button class="pri" id="memoNext">${last?'結果を見る':'次の項目へ →'}</button><button class="b" id="memoRetry">この項目をもう一度</button></div>`;document.getElementById('memoNext').onclick=()=>{idx++;renderQuestion()};document.getElementById('memoRetry').onclick=renderQuestion}
  function renderFull(item){const card=document.getElementById('memoCard');card.innerHTML=`<div class="meta">第${idx+1}項目を、ヒントなしで一から入力</div><div class="q">第${idx+1}項目の内容を全文入力してください。</div><textarea class="memoFull" id="memoFullInput" placeholder="ここに全文を入力"></textarea><div class="acts"><button class="pri" id="memoReveal">答えを見る</button></div>`;document.getElementById('memoReveal').onclick=()=>{const v=document.getElementById('memoFullInput').value.trim();if(!v&&!confirm('未入力で答えを見ますか？'))return;card.innerHTML=`<div class="meta">自分の回答</div><div class="memoAnswer">${esc(v||'（未入力）')}</div><div class="meta" style="margin-top:12px">正答</div><div class="memoAnswer">${esc(item.text)}</div><div class="sub" style="margin-top:10px">内容を見比べて自己採点してください。</div><div class="acts"><button class="pri" data-grade="ok">○ 覚えた</button><button class="b" data-grade="mid">△ 惜しい</button><button class="b danger" data-grade="ng">× 覚え直す</button></div>`;card.querySelectorAll('[data-grade]').forEach(b=>b.onclick=()=>{mark(b.dataset.grade);idx++;renderQuestion()})}}
  function renderFinish(){state.sessionStarted=false;save();const main=app(),set=TRACKS[track],summary=progressSummary(track,level);main.innerHTML=`<div data-memo-root><div class="box"><div class="ttl">${esc(set.title)}｜完了</div><div class="q">第1項目から第${set.items.length}項目まで順番に完了しました。</div><div class="sub" style="margin-top:8px">この難易度で一度でも○になった項目：${summary.ok}/${summary.total}</div><div class="acts"><button class="pri" id="memoAgain">もう一度1から</button><button class="b" id="memoHome">覚書トップ</button></div></div></div>`;document.getElementById('memoAgain').onclick=()=>{idx=0;state.sessionStarted=true;save();renderQuestion()};document.getElementById('memoHome').onclick=renderHome}
  window.addEventListener('DOMContentLoaded',ensureLauncher);
})();